### ISSUE TITLE
Downloaded all the newest files and did what https://www.youtube.com/watch?v=9IUaJmdR59 said but still does not work.

### ISSUE THREAD

**Issue by Bonjawa** [ClxS/SMAPI#111]
Here you go my friend.
Message: Object reference not set to an instance of an object.
InnerException: 
Stack Trace:    at Microsoft.Xna.Framework.Audio.SoundBank.PlayCue(String name)
   at StardewValley.Game1.playSound(String cueName)
   at StardewValley.TemporaryAnimatedSprite.update(GameTime time)
   at StardewValley.GameLocation.updateEvenIfFarmerIsntHere(GameTime time, Boolean ignoreWasUpdatedFlush)
   at StardewValley.Game1.UpdateLocations(GameTime time)
   at StardewValley.Game1.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at StardewValley.Program.Main(String[] args)

**Comment by ClxS** [comment]
Mmm this looks like something entirely caused by Stardew and not SMAPI. What version of SDV are you using?

**Comment by Bonjawa** [comment]
I keep my SDV at the "Always keep this game up to date" option in the Steam Stardew Valley - Properties.

**Comment by Bonjawa** [comment]
Sorry for me replying not that quick, I was sleeping.

**Comment by Bonjawa** [comment]
Also the latest update was on the 29th of april.

**Comment by Bonjawa** [comment]
Hello?

**Comment by Bonjawa** [comment]
Here is the most recent Error.

Stack Trace:    at System.Number.ParseNumber(Char*& str, NumberStyles options, NumberBuffer& number, StringBuilder sb, NumberFormatInfo numfmt, Boolean parseDecimal)
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at StardewValley.Menus.InventoryMenu.hover(Int32 x, Int32 y, Item heldItem)
   at StardewValley.Menus.InventoryPage.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Menus.GameMenu.performHoverAction(Int32 x, Int32 y)
   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at StardewValley.Program.Main(String[] args)

**Comment by Bonjawa** [comment]
Please help as soon as possible.
Thanks!

**Comment by ClxS** [comment]
Hi there,
Just to check, does the game run as normal without SMAPI?

**Comment by Bonjawa** [comment]
Yes and it runs fine with SMAPI.

**Comment by ClxS** [comment]
Mmm I'd suggest posting a thread over in the forum here: http://community.playstarbound.com/forums/mods.215/

Haven't ran into this error before and I'm not too sure if SMAPI is causing it.

**Comment by Bonjawa** [comment]
UGH just want to have fun.
But for me its a https://www.youtube.com/watch?v=ZZEV42bX9jc

**Comment by Bonjawa** [comment]
Also you have steam?
(Wanna be friends, I have no friends.......)

**Comment by Bonjawa** [comment]
Could we maybe go on skype and I could retry everything and have the power of you to guide me.

**Comment by Bonjawa** [comment]
Please....

**Comment by ClxS** [comment]
Sorry wont be able to, I'm not at home at the moment :).
What mods are you trying to use right now?

**Comment by Bonjawa** [comment]
CJB Item Spawner Mod

**Comment by ClxS** [comment]
Anddd does SMAPI work when you're not trying to use that mod?

**Comment by Bonjawa** [comment]
I tried Cheat menu also and the same thing.

**Comment by Bonjawa** [comment]
Its not the mod. its SMAPI or SDV.

**Comment by ClxS** [comment]
My guess is that it's something to do with your audio. If the game plays fine without SMAPI I suggest playing without mods now and maybe asking on the forum to see if anyone else has run into it.
