### ISSUE TITLE
Help My StarDew Valley mods wont work

### ISSUE THREAD

**Issue by Shizuko12** [ClxS/SMAPI#114]
Im on windows 10

C:\Users\Cherri\AppData\Roaming\StardewValley\ErrorLogs\MODDED_ProgramLog.Log_LATEST.txt
System.TypeInitializationException: The type initializer for 'StardewModdingAPI.Log' threw an exception. ---> System.IO.IOException: The process cannot access the file 'C:\Users\Cherri\AppData\Roaming\StardewValley\ErrorLogs\MODDED_ProgramLog.Log_LATEST.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at StardewModdingAPI.LogWriter.get_Instance()
   at StardewModdingAPI.Log..cctor()
   --- End of inner exception stack trace ---
   at StardewModdingAPI.Log.AsyncY(Object message)
   at StardewModdingAPI.Program.Main(String[] args)

**Comment by Gormogon** [comment]
@Shizuko12 Are you still receiving this error?  I'm not sure why, but it looks like another process was still accessing the log file when you tried to launch SMAPI so it was unable to write to the log.

**Comment by Pathoschild** [comment]
Since there's been no response in several months, I'll close the ticket now. Feel free to reopen if it still happens.
