### ISSUE TITLE
I have run into an issue

### ISSUE THREAD

**Issue by calebXD** [ClxS/SMAPI#119]
when i try to run the mod api i get this error
[03:27:04.296 PM] Game failed to start: System.MissingMethodException: Method not found: 'Int32 StardewValley.Game1.getMouseX()'.
   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at StardewModdingAPI.Program.RunGame()

**Comment by ClxS** [comment]
What version of Stardew are you using?

**Comment by dwiGalih** [comment]
i have the same exact problem withcaleb, my game version is 2.2.0.4, and i have installed .net framework 4.6.1, but still has the problem, can you help me please.

**Comment by TheMate39** [comment]
Had the exact same problem, managed to turn it into this:
http://prntscr.com/cadop1
Hope this gets solved, I'd love to play with some mods!

**Comment by Pathoschild** [comment]
Hello @calebXD, @dwiGalih, and @TheMate39. If this still happens with the latest version of Stardew Valley and SMAPI, come ask for help in the [Stardew Valley Discord](https://discord.gg/KCJHWhX) or the [discussion thead on the official forums](http://community.playstarbound.com/threads/stardew-modding-api-0-40-1-1.108375/) and we'll help you figure it out. :)
