### ISSUE TITLE
SMAPI crashes when I try to open the map

### ISSUE THREAD

**Issue by NotJenn** [ClxS/SMAPI#147]
I deleted my game folder and reinstalled Stardew valley but every time I try to open the map in the Modding API the game crashes.
This is the error that pops up:
[06:20:16.687 PM] An exception occured in XNA UpdateTick: System.MissingFieldException: Field not found: 'StardewValley.Game1.content'.
   at NPCMapLocations.MapPageTooltips..ctor(String names, Int32 nameTooltipMode)
   at NPCMapLocations.MapModMain.GameEvents_UpdateTick(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at StardewModdingAPI.Events.GameEvents.InvokeUpdateTick() in Z:\Projects\SMAPI\src\StardewModdingAPI\Events\Game.cs:line 80
[06:20:16.699 PM] [ERROR] An error occured in the overridden draw loop: System.NullReferenceException: Object reference not set to an instance of an object.
   at NPCMapLocations.MapModMain.drawMarkers(GameMenu menu)
   at NPCMapLocations.MapModMain.GraphicsEvents_OnPostRenderEvent(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at StardewModdingAPI.Events.GraphicsEvents.InvokeOnPostRenderGuiEvent(Object sender, EventArgs e) in Z:\Projects\SMAPI\src\StardewMod
D:\SteamLibrary\steamapps\common\Stardew Valley>

I'm not sure if there's something effecting it on my end or how to fix it

**Comment by Catinks** [comment]
It hasn't updated yet, the latest version of Stardew Valley is 1.11, SMAPI only supports (at the moment) ver. 1.1
So unless you can roll-back or have a GOG copy at ver.1.1, you'll have to wait unfortunately.

**Comment by ClxS** [comment]
This is likely a probelm with NPCMapLocations, not SMAPI.

**Comment by NotJenn** [comment]
I thought that might have been it as well Clxs so I completely uninstalled all mods, deleted the Stardew folder, removed everything from the NPC Map Locations mod and did a clean install of Stardew, and still experienced this problem.

**Comment by ClxS** [comment]
Mmm weird. Do you still get the same error output as the above after you've deleted your mods folder?

**Comment by thakyZ** [comment]
I wanted to let you know I am currently using SMAPI 0.40.1.1-3 and I am not having any issues with NPC Map locations.

**Comment by NotJenn** [comment]
Yup, same error

**Comment by ClxS** [comment]
You definitely have an outdated copy of NPC Locations hidden somewhere then.
Check both the mod folder that next to your game exe and the one in %Appdata%/Stardew Valley

**Comment by Pathoschild** [comment]
Make sure you're running the latest version of the [NPC Map Locations mod](http://www.nexusmods.com/stardewvalley/mods/239/), which has been updated for 1.1+. If you have any trouble, feel free to contact the author from the mod page.
