### ISSUE TITLE
Error in cmd after [Starting game...]

### ISSUE THREAD

**Issue by RoboJock** [ClxS/SMAPI#180]
This is the error. 
[15:55:31 ERROR SMAPI] SMAPI encountered a fatal error:
System.MissingMethodException: Method not found: 'Void StardewModdingAPI.Command.CallCommand(System.String)'.
   at SerializerUtils.SerializerUtility.Event_GameLoaded(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at StardewModdingAPI.Events.GameEvents.InvokeGameLoaded() in D:\source\SMAPI\src\StardewModdingAPI\Events\GameEvents.cs:line 52
   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime) in D:\source\SMAPI\src\StardewModdingAPI\Inheritance\SGame.cs:line 321
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at StardewModdingAPI.Program.StartGame() in D:\source\SMAPI\src\StardewModdingAPI\Program.cs:line 256

Note: My install directory for SV is my C: drive but I have backups on my D: for when I run out of space.

**Comment by Pathoschild** [comment]
@RoboJock: I see you closed this; did you figure out the problem?

**Comment by RoboJock** [comment]
Yes, it was the starbomb mod.
