### ISSUE TITLE
Problems with SMAPI

### ISSUE THREAD

**Issue by JanKolaric** [ClxS/SMAPI#99]
Exactly what it says when i start SMAPI:

C:\Users\My pc name\AppData\Roaming\StardewValley\ErrorLogs\MODDED_ProgramLog.Log_LATEST.txt
Created log instance
[10:43:39.542 ] SDV Version: 1.03
[10:43:39.546 ] SMAPI Version: 0.39.7 Alpha
[10:43:39.614 ] Initializing SDV Assembly...
[10:43:39.614 ] Injecting New SDV Version...
[10:43:39.616 ] Starting SDV...
[10:43:39.614 ] Validating api paths...
[10:43:39.711 ] Patching SDV Graphics Profile...
[10:43:39.785 ] Found Manifest: C:\GOG Games\Stardew Valley\Mods\TrainerMod\manifest.json
[10:43:39.742 ] LOADING MODS
[10:43:40.218 ] Created psconfigs directory @C:\GOG Games\Stardew Valley\Mods\TrainerMod\psconfigs
[10:43:40.232 ] LOADED MOD: Trainer Mod by Zoryn - Version StardewModdingAPI.Version | Description: Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating. (@ C:\GOG Games\Stardew Valley\Mods\TrainerMod\TrainerMod.dll)
[10:43:40.234 ] Registered command: types
[10:43:40.234 ] Registered command: hide
[10:43:40.237 ] Registered command: show
[10:43:40.257 ] Registered command: load
[10:43:40.232 ] Loading Mod DLL...
[10:43:40.260 ] Registered command: exit
[10:43:40.254 ] Registered command: save
[10:43:40.264 ] Registered command: player_setmoney
[10:43:40.266 ] Registered command: player_setstamina
[10:43:40.270 ] Registered command: player_setmaxstamina
[10:43:40.260 ] Registered command: stop
[10:43:40.263 ] Registered command: player_setname
[10:43:40.274 ] Registered command: player_setimmunity
[10:43:40.275 ] Registered command: player_setlevel
[10:43:40.273 ] Registered command: player_setmaxhealth
[10:43:40.272 ] Registered command: player_sethealth
[10:43:40.281 ] Registered command: player_changestyle
[10:43:40.280 ] Registered command: player_changecolour
[10:43:40.284 ] Registered command: player_addmelee
[10:43:40.278 ] Registered command: player_setspeed
[10:43:40.282 ] Registered command: player_additem
[10:43:40.289 ] Registered command: out_melee
[10:43:40.286 ] Registered command: player_addring
[10:43:40.287 ] Registered command: out_items
[10:43:40.291 ] Registered command: out_rings
[10:43:40.298 ] Registered command: world_freezetime
[10:43:40.301 ] Registered command: world_setday
[10:43:40.294 ] Registered command: newitem
[10:43:40.294 ] Registered command: world_settime
[10:43:40.305 ] Registered command: world_setminelevel
[10:43:40.308 ] LOADED 1 MODS
[10:43:40.304 ] Registered command: world_downminelevel
[10:43:40.303 ] Registered command: world_setseason
[10:43:40.317 ] Registered command: help
[10:43:40.318 ] Applying Final SDV Tweaks...
[10:43:40.316 ] Initializing Console Input Thread...
[10:43:40.314 ] SDV Loaded Into Memory
[10:43:40.466 ] XNA Initialize
[10:43:51.000 ] XNA LoadContent
[10:44:01.070 ] Initializing Debug Assets...
[10:44:01.596 ] Game failed to start: System.MissingMethodException: Method not found: 'Int32 StardewValley.Game1.getMouseX()'.
   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at StardewModdingAPI.Program.RunGame()
System.ComponentModel.InvalidAsynchronousStateException: An error occurred invoking the method.  The destination thread no longer exists.
   at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at StardewModdingAPI.Program.StardewInvoke(Action a)
   at StardewModdingAPI.Program.ConfigureSDV()
   at StardewModdingAPI.Program.Main(String[] args)

**Comment by CJBok** [comment]
Make sure you have version 1.07 installed of Stardew Valley.

**Comment by JanKolaric** [comment]
how do i check the version?
